name: Monitor de Ativos B3

on:
  schedule:
    # O horário UTC é 3h a mais que Brasília.
    # 13:00 às 21:00 UTC = 10:00 às 18:00 Brasília.
    # Roda a cada 30 minutos, de segunda a sexta-feira.
    - cron: '*/10 13-21 * * 1-5'
  workflow_dispatch: # Permite que você rode o teste manualmente pelo botão "Run workflow"

jobs:
  check-prices:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar Bibliotecas
        run: |
          pip install yfinance requests

      - name: Executar Script de Monitoramento
        env:
          # Estas variáveis devem ser configuradas nos "Secrets" do seu GitHub
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python monitor.py
